### ISSUE TITLE
Nao funciona!

### ISSUE THREAD

**Issue by saiber0007** [devRogi/GrowBotPremium#1]
Tentei utilizar, mas assim que instala ele diz que o periodo de teste já acabou (Your free trial has ended.)

![image](https://github.com/devRogi/GrowBotPremium/assets/172852680/1874b851-1e07-4a2d-8464-6e6f82e63441)

**Comment by devRogi** [comment]
fez a instalação conforme indicado? removeu a versão oficial (caso estivesse utilizando) do grow? caso tenha feito tudo certo e mesmo assim ainda aparece isso, tenta utilizar a versão mais recente no release!

**Comment by saiber0007** [comment]
Opa! Fiz sim, exatamente igual esta explicando, até tentei no num navegador zerado sem extensors do chrome, tentei pelo dolphin, tentei em outro pc.. qual loga o insta, ele diz que expirou.
Tentei as duas versoes que tem disponivel 2.2.4 e 2.2.2, mesmo problema em ambos.
Vc tentou utilizar com outro instagram?
Se puder me ajudar agradeço,  abraço

**Comment by devRogi** [comment]
Olá! Gostaríamos de informar que a versão 2.3.0 já está disponível para download. Por favor, teste-a para verificar se o erro mencionado ainda persiste. Caso contrário, não há muito o que fazer, pois o arquivo zip foi testado em várias máquinas e nenhum problema foi encontrado. Aguardamos seu feedback!

**Comment by saiber0007** [comment]
Deu certo! Funcionou certinho essa versão nova. Muito obrigado mesmo, ajudou muito! Meus parabéns pelo trabalho
