### ISSUE TITLE
growbot ta pendendo para pagar

### ISSUE THREAD

**Issue by renatotoic** [devRogi/GrowBotPremium#2]
growbot ta pendendo para pagar

**Comment by devRogi** [comment]
você baixou a ultima versão disponivel em https://github.com/devRogi/GrowBotPremium/releases

**Comment by agcvm87** [comment]
@devRogi é para baixar os 3 arquivos ou apenas 1 deles?
Notei que quando uso o search code ele pede para pagar.

**Comment by devRogi** [comment]
baixa so o arquivo "2.2.3.0_0.zip"
