### ISSUE TITLE
Não está carregando lista de quem comentou ou deu like, apenas seguidores

### ISSUE THREAD

**Issue by dibraldinhowxf** [devRogi/GrowBotPremium#9]
Quando clico na opção pra carregar quem comentou ou deu like acontece um erro na extensão

![Screenshot_2](https://github.com/user-attachments/assets/4502cd59-9883-4681-9033-33a62b1fa280)

**Comment by devRogi** [comment]
test the new version of GrowBot 2.3.4 available in release

**Comment by dibraldinhowxf** [comment]
working now ty
